### ISSUE TITLE
LTC Wallet wont work anymore

### ISSUE THREAD

**Issue by henriAbel** [sereneblue/blt-wallet#2]
Same origin policy error when accessing any Litecoin wallet
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://testnet.litecore.io/api/addr/mh2B6DddWtZAgZSyoZHAHe81kxX23zp2Xm. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by sereneblue** [comment]
Was the website down for you when you tested it?

**Comment by henriAbel** [comment]
Seems that testnet.litecore.io/api site is down. I only get Cloudflare error page when opening link in browser.

**Comment by sereneblue** [comment]
I'm surprised it's still down; will look around for an alternative.

**Comment by sereneblue** [comment]
https://testnet.litecore.io is back up again! I don't think there are any other public testnet explorers for Litecoin besides chain.so (unreliable) and litecore.
